#####################################
# 2018 ithome ironman
# Author: James Lu
# Topic: k8s 不自賞 - Day 14 Volume (1) 
# Url: https://ithelp.ithome.com.tw/articles/10193546
# Licence: MIT
#####################################

apiVersion: v1
kind: Pod
metadata:
  name: volume-hostpath-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /tmp/conf
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/hostpathdata
      type: Directory

